require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/formula_also_knowns", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # FormulaAlsoKnown. As you add validations to FormulaAlsoKnown, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # FormulaAlsoKnownsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      FormulaAlsoKnown.create! valid_attributes
      get formula_also_knowns_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      formula_also_known = FormulaAlsoKnown.create! valid_attributes
      get formula_also_known_url(formula_also_known), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FormulaAlsoKnown" do
        expect {
          post formula_also_knowns_url,
               params: { formula_also_known: valid_attributes }, headers: valid_headers, as: :json
        }.to change(FormulaAlsoKnown, :count).by(1)
      end

      it "renders a JSON response with the new formula_also_known" do
        post formula_also_knowns_url,
             params: { formula_also_known: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FormulaAlsoKnown" do
        expect {
          post formula_also_knowns_url,
               params: { formula_also_known: invalid_attributes }, as: :json
        }.to change(FormulaAlsoKnown, :count).by(0)
      end

      it "renders a JSON response with errors for the new formula_also_known" do
        post formula_also_knowns_url,
             params: { formula_also_known: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested formula_also_known" do
        formula_also_known = FormulaAlsoKnown.create! valid_attributes
        patch formula_also_known_url(formula_also_known),
              params: { formula_also_known: new_attributes }, headers: valid_headers, as: :json
        formula_also_known.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the formula_also_known" do
        formula_also_known = FormulaAlsoKnown.create! valid_attributes
        patch formula_also_known_url(formula_also_known),
              params: { formula_also_known: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the formula_also_known" do
        formula_also_known = FormulaAlsoKnown.create! valid_attributes
        patch formula_also_known_url(formula_also_known),
              params: { formula_also_known: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested formula_also_known" do
      formula_also_known = FormulaAlsoKnown.create! valid_attributes
      expect {
        delete formula_also_known_url(formula_also_known), headers: valid_headers, as: :json
      }.to change(FormulaAlsoKnown, :count).by(-1)
    end
  end
end
